SGE_GP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('meu-perfil/', MeuPerfilView.as_view(), name='my-profile'),
    path("disciplinas/", DisciplinasView.as_view(), name="subjects"),
    path("disciplinas/<int:pk>/desempenho/", DesempenhoView.as_view(), name="performance"),
    path("lancar-aula/", LancarAulaView.as_view(), name="launch-class"),
    path('get_students_for_subject/', get_students_for_subject, name='get_students_for_subject'),
    path("professores/", ProfessoresView.as_view(), name="teachers"),
    # Avaliações
    path("avaliacoes/<str:slug>", TestsView.as_view(), name="tests"),
    path("avaliacoes/<str:slug>/abrir/", AbrirAvaliacaoView.as_view(), name="open-test"),
    path("avaliacoes/<int:pk>/", GradesView.as_view(), name="grades"),
    # Eventos
    path("eventos/", EventosView.as_view(), name="events"),
    path("eventos/<int:pk>/", EventoView.as_view(), name="event"),
    path("eventos/<int:pk>/editar/", EditarEvento.as_view(), name="edit-event"),
    path("criar-evento/", CriarEvento.as_view(), name="create-event"),
    path("eventos/<int:pk>/deletar/", DeletarEvento.as_view(), name="delete-event"),
    # Turmas
    path("turmas/", TurmasView.as_view(), name="classes"),
    path('turmas/<int:pk>/', TurmaDetailView.as_view(), name='class'),
    path('turmas/<int:pk>/editar', TurmaUpdateView.as_view(), name='edit-class'),
    path("turmas/criar/", TurmaCreateView.as_view(), name="create-class"),
    # Atividades
    path("disciplinas/<str:slug>/atividades/", ActivityListView.as_view(), name="activities"),
    path("disciplinas/<str:slug>/atividades/<int:pk>/", ActivityDetailView.as_view(), name="activity"),
    path("disciplinas/<str:slug>/atividades/criar/", ActivityCreateView.as_view(), name="create-activity"),
    path("disciplinas/<str:slug>/atividades/<int:pk>/editar/", ActivityUpdateView.as_view(), name="edit-activity"),
    path("disciplinas/<str:slug>/atividades/<int:pk>/deletar/", ActivityDeleteView.as_view(), name="delete-activity"),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Candal' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'main/styles/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="{% static 'main/icons/CEGP.svg' %}" type="image/x-icon">

    <meta name="author" content="Greentech" />
    <link rel="canonical" href="https://clediston.pythonanywhere.com/"/>
    <meta name="description" content='Sistema de Gestão Educacional para o Centro de Estudos Geraldo Palmeira' />
    <meta name="geo.placename" content="Colégio Geraldo Palmeira">
    <meta name="geo.region" content="BR-PA" />
    <meta name="geo.position" content="-1.4302242685141513-48.48524283037325" />
    <meta name="ICBM" content="-1.4302242685141513;-48.48524283037325" />
    <meta http-equiv="content-language" content="pt-br" />
    <meta name="copyright" content="© 2024 SGE-GP" />
    <meta name="generator" content="Django.py 4.2.7" />
    <meta name="rating" content="general" />
    <!-- Meta Tags da META (Facebook) -->
    <meta property="og:title" content="SGE-GP"/>
    <meta property="og:description" content='Sistema de Gestão Educacional para o Centro de Estudos Geraldo Palmeira'/>
    <meta property="og:url" content="http://clediston.pythonanywhere.com/"/>
    <meta property="og:site_name" content="SGE-GP"/>
    <!-- Meta Tags do Twitter -->
    <meta name="twitter:title" content="SGE-GP">
    <meta name="twitter:description" content='Sistema de Gestão Educacional para o Centro de Estudos Geraldo Palmeira'>
    <meta name="twitter:url" content="https://clediston.pythonanywhere.com/">
    <meta name="twitter:card" content="summary">
    <!-- Meta Tags de Imagem -->
    <meta property="og:image" content="https://clediston.pythonanywhere.com{% static 'main/images/CEGP.jpg' %}" />
    <meta name="twitter:image" content="https://clediston.pythonanywhere.com{% static 'main/images/CEGP.jpg' %}" />
    <meta property="og:type" content="website"/>
    {% block head %}{% endblock head %}
  </head>
  <body class="d-flex flex-column">

    <header>
      <nav id="navbar" class="navbar bg-green mb-5" data-bs-theme="dark">
        <div class="container-fluid justify-content-between text-white">
          <a class="navbar-brand fs-3" href="{% url 'main:index' %}">
            <img class="me-2" src="{% static 'main/icons/CEGP.svg' %}" alt="Logo do Colégio Geraldo Palemeira">
            SGE-GP  
          </a>
          {% if not user.is_authenticated %}
          <div>
            <a class="btn btn-light fw-bold text-green btn-navbar rounded-pill me-3" id="botaoLogin" href="{% url 'account_login' %}" role="button">Entrar</a>
            <a class="btn bg-light-green fw-bold text-dark-green btn-navbar rounded-pill" id="botaoCadastro" href="{% url 'account_signup' %}" role="button">Cadastre-se</a>
          </div>
          {% else %}
          <div class="d-md-flex">
            {% if request.resolver_match.url_name == 'index' %}
            <a class="btn bg-light-green btn-navbar text-dark-green fw-bold rounded-pill me-3" href="{% url 'main:subjects' %}" role="button">Ver sistema</a>
            {% endif %}
            <a class="btn btn-danger btn-navbar fw-bold rounded-pill d-none d-md-block" href="{% url 'account_logout' %}" role="button">Sair</a>
          </div>
            {% if request.resolver_match.url_name != 'index' %}
            <button class="navbar-toggler d-md-none" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
              <i class="bi bi-list fw-bold text-white fs-1"></i>
            </button>
            <ul id="navbarToggler" class="navbar-nav collapse navbar-collapse mt-2 me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:my-profile' %}">Meu Perfil</a>
              </li>
              {% if user.type == 'guardian' or user.type == 'student' %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:subjects' %}">Disciplinas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:events' %}">Eventos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:teachers' %}">Professores</a>
              </li>
              {% elif user.type == 'teacher' %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:subjects' %}">Disciplinas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:events' %}">Eventos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:launch-class' %}">Lançar Aula</a>
              </li>
              {% elif user.type == 'coordinator' %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:classes' %}">Turmas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:events' %}">Eventos</a>
              </li>
              {% endif %}
              {% if user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Administração</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="btn btn-danger btn-navbar fw-bold rounded-pill d-none d-md-block" href="{% url 'account_logout' %}" role="button">Sair</a>
              </li>
            </ul>
            {% endif %}
          {% endif %}
        </div>
      </nav>
    </header>

    {% for message in messages %}
      <div class="alert bg-warning alert-dismissible fade show border-0 rounded-0 m-0 mb-3" role="alert" id="alert">
        <strong>Mensagem:</strong> {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% empty %}
      <!-- No messages -->
    {% endfor %}

    {% block container %}
    <main class="container">
        <div class="row justify-content-center g-md-5">
            {% block aside %}{% endblock aside %}
            {% block content %}{% endblock content %}
        </div>
    </main>
    {% endblock container %}
    

    <footer class="{% if request.resolver_match.url_name != 'index' %}mt-5{% endif %}">
        <nav class="navbar bg-dark" data-bs-theme="dark">
            <div class="container-fluid justify-content-center">
                <img src="{% static 'main/icons/CEGP.svg' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
            </div>
          </nav>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static 'main/scripts/scripts.js' %}"></script>
  </body>
  {% block script %}{% endblock script %}
</html>