SGE_GP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('meu-perfil/', MeuPerfilView.as_view(), name='my-profile'),
    path("disciplinas/", DisciplinasView.as_view(), name="subjects"),
    path("disciplinas/<int:pk>/desempenho/", DesempenhoView.as_view(), name="performance"),
    path("lancar-aula/", LancarAulaView.as_view(), name="launch-class"),
    path('get_students_for_subject/', get_students_for_subject, name='get_students_for_subject'),
    path("professores/", ProfessoresView.as_view(), name="teachers"),
    # Avaliações
    path("avaliacoes/<str:slug>", TestsView.as_view(), name="tests"),
    path("avaliacoes/<str:slug>/abrir/", AbrirAvaliacaoView.as_view(), name="open-test"),
    path("avaliacoes/<int:pk>/", GradesView.as_view(), name="grades"),
    # Eventos
    path("eventos/", EventosView.as_view(), name="events"),
    path("eventos/<int:pk>/", EventoView.as_view(), name="event"),
    path("eventos/<int:pk>/editar/", EditarEvento.as_view(), name="edit-event"),
    path("criar-evento/", CriarEvento.as_view(), name="create-event"),
    path("eventos/<int:pk>/deletar/", DeletarEvento.as_view(), name="delete-event"),
    # Turmas
    path("turmas/", TurmasView.as_view(), name="classes"),
    path('turmas/<int:pk>/', TurmaDetailView.as_view(), name='class'),
    path('turmas/<int:pk>/editar', TurmaUpdateView.as_view(), name='edit-class'),
    path("turmas/criar/", TurmaCreateView.as_view(), name="create-class"),
    # Atividades
    path("disciplinas/<str:slug>/atividades/", ActivityListView.as_view(), name="activities"),
    path("disciplinas/<str:slug>/atividades/<int:pk>/", ActivityDetailView.as_view(), name="activity"),
    path("disciplinas/<str:slug>/atividades/criar/", ActivityCreateView.as_view(), name="create-activity"),
    path("disciplinas/<str:slug>/atividades/<int:pk>/editar/", ActivityUpdateView.as_view(), name="edit-activity"),
    path("disciplinas/<str:slug>/atividades/<int:pk>/deletar/", ActivityDeleteView.as_view(), name="delete-activity"),
]

main/models.py
from django.db import models
from django.utils.text import slugify


class Subject(models.Model):
    name = models.CharField("Nome", max_length=50)
    syllabus = models.TextField("Ementa", blank=True, null=True)
    class_code = models.ForeignKey(
        "Class", on_delete=models.CASCADE, verbose_name="Turma"
    )
    academic_probation = models.ManyToManyField(
        "accounts.User", related_name="academic_probation", verbose_name="Dependência", blank=True
    )
    teacher = models.ForeignKey('accounts.User', on_delete=models.CASCADE, verbose_name='Professor', blank=True, null=True)
    slug = models.SlugField(max_length=200, editable=False, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.name} {self.class_code}")
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name + " - " + str(self.class_code)

    class Meta:
        verbose_name = "Disciplina"
        verbose_name_plural = "Disciplinas"


class Class(models.Model):
    LEVELS = (
        ("M", "Maternal"),
        ("J1", "Jardim 1"),
        ("J2", "Jardim 2"),
        ("1", "1ª Ano"),
        ("2", "2ª Ano"),
        ("3", "3ª Ano"),
        ("4", "4ª Ano"),
        ("5", "5ª Ano"),
        ("6", "6ª Ano"),
        ("7", "7ª Ano"),
        ("8", "8ª Ano"),
        ("9", "9ª Ano"),
        ("1M", "1º Ano - Médio"),
        ("2M", "2º Ano - Médio"),
        ("3M", "3º Ano - Médio"),
    )

    code = models.CharField("Código", max_length=10)
    level = models.CharField("Nível", max_length=50, choices=LEVELS)
    enrolled = models.ManyToManyField(
        "accounts.User", related_name="matriculados", verbose_name="Matriculados", blank=True
    )
    academic_year = models.IntegerField("Ano Letivo")

    class Meta:
        verbose_name = "Turma"
        verbose_name_plural = "Turmas"

    def __str__(self):
        return self.code + " - " + self.level + " - " + str(self.academic_year)


class Classroom(models.Model):
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, verbose_name="Disciplina"
    )
    class_code = models.ForeignKey(
        Class, on_delete=models.CASCADE, verbose_name="Turma"
    )
    date = models.DateField("Data")
    attendance_list = models.ManyToManyField(
        "accounts.User",
        related_name="students_present",
        verbose_name="lista de presença",
    )
    class_diary = models.TextField("Diário de Classe")
    
    def get_absent_students(self):
        all_students = set(self.class_code.enrolled.all())
        present_students = set(self.attendance_list.all())
        absent_students = all_students - present_students
        return absent_students

    class Meta:
        verbose_name = "Aula"
        verbose_name_plural = "Aulas"

    def __str__(self):
        return str(self.subject.name) + " - " + str(self.class_code) + " - " + str(self.date)

class Test(models.Model):
    TESTS = (
        ("1", "1ª Avaliação"),
        ("2", "2ª Avaliação"),
        ("3", "3ª Avaliação"),
        ("4", "4ª Avaliação"),
        ("PF", "Prova Final"),
    )

    school_test = models.CharField("Prova", max_length=50, choices=TESTS)
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, verbose_name="Disciplina"
    )
    class_code = models.ForeignKey(
        Class, on_delete=models.CASCADE, verbose_name="Turma"
    )
    date = models.DateField("Data")

    class Meta:
        verbose_name = "Prova"
        verbose_name_plural = "Provas"

    def __str__(self):
        return self.get_school_test_display() + " de " + self.subject.name + " - " + str(self.class_code)


class Grade(models.Model):
    student = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, verbose_name="Aluno"
    )
    test = models.ForeignKey(Test, on_delete=models.CASCADE, verbose_name="Prova")
    grade = models.FloatField("Nota")

    class Meta:
        verbose_name = "Nota"
        verbose_name_plural = "Notas"

    def __str__(self):
        return (
            self.student.first_name
            + " - "
            + self.test.school_test
            + " - "
            + self.test.subject.name
            + " - "
            + str(self.test.class_code)
        )


class Activity(models.Model):
    title = models.CharField("Título", max_length=50)
    prompt = models.TextField("Enunciado")
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, verbose_name="Disciplina"
    )
    image = models.ImageField('Imagem', upload_to='main/activities', blank=True, null=True)
    creation_date = models.DateField("Data de criação", auto_now_add=True)
    delivery_date = models.DateField("Data de entrega")

    class Meta:
        verbose_name = "Atividade"
        verbose_name_plural = "Atividades"

    def __str__(self):
        return self.title


class Event(models.Model):
    image = models.ImageField('Imagem', upload_to='main/events', blank=True, null=True)
    title = models.CharField("Título", max_length=50)
    description = models.TextField("Descrição")
    date_time = models.DateTimeField("Data e Hora")
    enrolled = models.ManyToManyField(
        "accounts.User", related_name="participants", verbose_name="Participantes", blank=True
    )

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"

    def __str__(self):
        return self.title

main/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView

from .forms import ClassroomForm, TestForm, GradeForm
from accounts.models import User
from .models import *


class IndexView(TemplateView):
    template_name = "main/index.html"


class MeuPerfilView(LoginRequiredMixin, TemplateView):
    template_name = "main/meu-perfil.html"


class DisciplinasView(LoginRequiredMixin, ListView):
    model = Subject
    template_name = "main/disciplinas.html"
    context_object_name = "subjects"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.type == "teacher":
            context["subjects"] = Subject.objects.filter(teacher=self.request.user)
        elif self.request.user.type == "student":
            student = self.request.user
            try:
                student_class = Class.objects.get(enrolled=student)
                context["subjects"] = Subject.objects.filter(class_code=student_class)
            except Class.DoesNotExist:
                context["subjects"] = None
        return context
    
    
class DesempenhoView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Subject
    template_name = "main/desempenho.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        grades = Grade.objects.filter(student=self.request.user, test__subject=self.get_object())
        grades_dict = {grade.test.school_test: grade for grade in grades}
        context["grades"] = grades_dict
        
        # Calcula a média do aluno
        # Passo 1: Verifique se todas as notas estão presentes
        if all(grade in grades_dict for grade in ['1', '2', '3', '4']):
            # Passo 2: Calcule a média das primeiras 4 notas
            average = sum(grades_dict[grade].grade for grade in ['1', '2', '3', '4']) / 4

            # Passo 3: Verifique se há uma nota para a prova final
            if 'PF' in grades_dict:
                # Passo 4: Adicione a nota da prova final à média calculada e divida por 2
                average = (average + grades_dict['PF'].grade) / 2

            # Passo 5: Armazene o resultado na variável 'average'
            context["average"] = average

        # Get all the lessons of the subject
        lessons = Classroom.objects.filter(subject=self.get_object())

        # Get the student's absences
        absents = [lesson for lesson in lessons if self.request.user not in lesson.attendance_list.all()]
        context["absents"] = absents

        return context
    
    def test_func(self):    
        return self.request.user.type == "student"
    

def get_students_for_subject(request):
    subject = Subject.objects.get(id=request.GET.get('subject', None))
    students = subject.class_code.enrolled.all() | subject.academic_probation.all()
    student_list = [{'id': int(student.id), 'name': str(student)} for student in students]
    return JsonResponse(student_list, safe=False)


class LancarAulaView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Classroom
    form_class = ClassroomForm
    template_name = "main/lancar-aula.html"
    success_url = reverse_lazy("main:subjects")

    def get_form_kwargs(self):
        kwargs = super(LancarAulaView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs
    
    def form_valid(self, form):
        messages.success(self.request, "Aula lançada com sucesso!")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print(form.errors)
        messages.error(self.request, "Erro ao lançar aula.")
        return super().form_invalid(form)
    
    def test_func(self):    
        return self.request.user.type == "teacher" or self.request.user.type == "coordinator"
    

class ProfessoresView(LoginRequiredMixin, ListView):
    model = User
    template_name = "main/professores.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.type == "coordinator" or self.request.user.type == "teacher":
            context["teachers"] = User.objects.filter(type="teacher")
        else:
            try:
                student_class = Class.objects.get(enrolled=self.request.user)
                subjects = Subject.objects.filter(class_code=student_class)
                context["subjects"] = subjects
            except Class.DoesNotExist:
                context["subjects"] = None

        return context


class TestsView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Test
    template_name = "main/avaliacoes/avaliacoes.html"
    slug_field = "subject__slug"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tests"] = Test.objects.filter(subject__slug=self.kwargs["slug"])
        context["subject"] = Subject.objects.get(slug=self.kwargs["slug"])
        return context
    
    def test_func(self):    
        teacher = get_object_or_404(Subject, slug=self.kwargs['slug']).teacher
        return self.request.user == teacher or self.request.user.type == "coordinator"


class AbrirAvaliacaoView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Test
    form_class = TestForm
    template_name = "main/avaliacoes/abrir-avalicao.html"

    def get_success_url(self):
        return reverse_lazy("main:tests", kwargs={"slug": self.object.subject.slug})
    
    def get_form_kwargs(self):
        kwargs = super(AbrirAvaliacaoView, self).get_form_kwargs()
        subject = Subject.objects.get(slug=self.kwargs["slug"])
        kwargs.update({'user': self.request.user, 'subject': subject})
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["subject"] = Subject.objects.get(slug=self.kwargs["slug"])
        return context
    
    def test_func(self):    
        teacher = get_object_or_404(Subject, slug=self.kwargs['slug']).teacher
        return self.request.user == teacher or self.request.user.type == "coordinator"
    

class GradesView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Test
    template_name = "main/avaliacoes/notas.html"
    
    def test_func(self):    
        teacher = get_object_or_404(Test, pk=self.kwargs['pk']).subject.teacher
        return self.request.user == teacher or self.request.user.type == "coordinator"

    def get_success_url(self):
        return reverse_lazy("main:tests", kwargs={"slug": self.object.subject.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        students = self.object.subject.class_code.enrolled.all()
        student_form_pairs = []
        for student in students:
            grade = student.grade_set.filter(test=self.object).first()
            if grade is not None:
                grade.grade = str(grade.grade).replace(',', '.')
                grade.save()
            form = GradeForm(instance=grade)
            student_form_pairs.append((student, form))
        context['student_form_pairs'] = student_form_pairs
        return context

    def post(self, request, *args, **kwargs):   
        self.object = self.get_object()
        students = self.object.subject.class_code.enrolled.all()
        student_form_pairs = []
        for student in students:
            grade = student.grade_set.filter(test=self.object).first()
            if grade is None:
                grade = Grade(student=student, test=self.object)
            form = GradeForm(request.POST or None, prefix=str(student.id), instance=grade)
            if form.has_changed():
                if form.is_valid():
                    form.save()
                else:
                    print(f"Errors for student {student.id}: {form.errors}")
                    messages.error(request, "Erro ao lançar notas.")
                    return self.render_to_response(self.get_context_data(student_form_pairs=student_form_pairs))
            student_form_pairs.append((student, form))

        messages.success(request, "Notas lançadas com sucesso!")
        return redirect(self.get_success_url())
    
    
class EventosView(LoginRequiredMixin, ListView):
    model = Event
    template_name = "main/eventos/eventos.html"
    context_object_name = "events"
    
    
class EventoView(LoginRequiredMixin, DetailView):
    model = Event
    template_name = "main/eventos/evento.html"
    
    
class CriarEvento(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Event
    fields = ['image', 'title', 'description', 'date_time']
    template_name = "main/eventos/criar-evento.html"
    success_url = reverse_lazy("main:events")
    
    def test_func(self):    
        return self.request.user.type == "coordinator"
    

class EditarEvento(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Event
    fields = ['image', 'title', 'description', 'date_time']
    template_name = "main/eventos/criar-evento.html"
    success_url = reverse_lazy("main:events")
    
    def test_func(self):    
        return self.request.user.type == "coordinator"
    
    
class DeletarEvento(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Event

    def test_func(self):    
        return self.request.user.type == "coordinator"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy("main:events")
    

main/templates/main/desempenho.html
{% extends "base.html" %}

{% block title %}{{ object.name }} | Desempenho{% endblock title %}

{% block aside %}
{% include "main/snippets/aside.html" %}
{% endblock aside %}

{% block content %}
<div class="col-12 col-md-9">
    <h1 class="display-5 text-center mb-2">{{ object.name }}</h1>
    <div class="row row-cols-2 row-cols-md-4 justify-content-center align-items-center g-2">
        <div class="col">
            <div class="card card-assessment py-3">
                <div class="card-body d-flex flex-column justify-content-evenly text-center">
                    <h4 class="card-title assessment">1ª Avaliação</h4>
                    <h2 class="card-text grade">{{ grades.1.grade|default:"-" }}</h2>                    
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card card-assessment py-3">
                <div class="card-body d-flex flex-column justify-content-evenly text-center">
                    <h4 class="card-title assessment">2ª Avaliação</h4>
                    <h2 class="card-text grade">{{ grades.2.grade|default:"-" }}</h2>                    
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card card-assessment py-3">
                <div class="card-body d-flex flex-column justify-content-evenly text-center">
                    <h4 class="card-title assessment">3ª Avaliação</h4>
                    <h2 class="card-text grade">{{ grades.3.grade|default:"-" }}</h2>                    
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card card-assessment py-3">
                <div class="card-body d-flex flex-column justify-content-evenly text-center">
                    <h4 class="card-title assessment">4ª Avaliação</h4>
                    <h2 class="card-text grade">{{ grades.4.grade|default:"-" }}</h2>                    
                </div>
            </div>
        </div>
        {% if grades.PF.grade %}
        <div class="col">
            <div class="card card-assessment py-3">
                <div class="card-body d-flex flex-column justify-content-evenly text-center">
                    <h4 class="card-title assessment">Prova Final</h4>
                    <h2 class="card-text grade">{{ grades.PF.grade|default:"-" }}</h2>                    
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    {% if average %}      
    <div class="row justify-content-center mt-3">
        <div class="alert alert-{% if grades.PF.grade and average < 7 %}danger{% elif average >= 7 %}success{% elif average < 4 %}danger{% else %}warning border border-dark border-2{% endif %} text-center fs-4 w-50" role="alert">            <strong>Média final:</strong> {{ average }}
        </div>
    </div>
    {% endif %}
    <div class="row my-4">
        <h1 class="display-5 text-center my-4">
            Frequência
            <br>
            <small style="font-size: medium;">(Suas Faltas)</small>
        </h1>
        
        <div class="d-flex overflow-x-scroll w-100">
            <div class="d-flex">
                {% for absent in absents %}
                <div class="card card-frequency bg-danger me-3 ">
                    <div class="card-body text-center text-white fw-bold">
                        <h4 class="card-title">Data:</h4>
                        <h4 class="card-text fw-bold">{{ absent.date|date:'d/m' }}<br>{{ absent.date|date:'Y' }}</h4>
                    </div>
                </div>
                {% empty %}
                <div class="alert alert-success w-100" role="alert">
                    <strong>Não há faltas!</strong> Você nunca faltou nesta disciplina.
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{%endblock content%}

main/templates/main/disciplinas.html
{% extends "base.html" %}

{% block title %}SGE-GP | Disciplinas{% endblock title %}

{% block aside %}
  {% include "main/snippets/aside.html" %}
{% endblock aside %}

{% block content %}
<div class="col-9">
  <h1 class="d-md-none">Disciplinas</h1>
  <div class="col-12 col-sm-8 my-3">
    <div class="d-md-flex align-items-center justify-content-between">
      <div class="input-group me-1">
        <span class="input-group-text bg-dark-green text-light" id="basic-addon1"><i class="bi bi-search"></i></span>
        <input type="text" id="search-subject" class="form-control" placeholder="Por nome...">
      </div>
      <div class="input-group">
        <span class="input-group-text bg-dark-green text-light" id="basic-addon1"><i class="bi bi-search"></i></span>
        <input type="text" id="search-class" class="form-control" placeholder="Por turma...">
      </div>
    </div>
  </div>
  <div class="row {% if subjects %}row-cols-1 row-cols-md-2 row-cols-lg-4{% endif %} g-2">
    {% for subject in subjects %}
    <div class="col" data-id="{{ subject.name }}" data-class="{{ subject.class_code }}">
      <div class="card card-subject ratio ratio-1x1 rounded-4 bg-light-green">
        <div class="card-body d-flex flex-column justify-content-center text-center">
          <h4 class="card-title text-dark-green fw-bold">{{ subject.name }}</h4>
          {% if user.type != 'student' %}
          <p class="card-text text-dark-green">{{ subject.class_code }}</p>
          {% else %}
          <hr class='mt-1'>
          {% endif %}
          <div class="d-flex w-100">
            {% if user.type == 'teacher' or user.type == 'coordinator' %}
            <a href="{% url 'main:tests' subject.slug %}"
              class="btn bg-dark-green w-50 fw-bold rounded-4 me-2 d-flex flex-column align-items-center justify-content-center"
              role="button">
              <i class="bi bi-file-earmark-bar-graph fs-1"></i>
              <span>Avaliações</span>
            </a>
            {% else %}
            <a href="{% url 'main:performance' subject.pk %}"
              class="btn bg-dark-green w-50 fw-bold rounded-4 me-2 d-flex flex-column align-items-center justify-content-center"
              role="button">
              <i class="bi bi-file-earmark-bar-graph fs-1"></i>
              <span>Desempenho</span>
            </a>
            {% endif %}
            <a href="{% url 'main:activities' subject.slug  %}"
              class="btn bg-dark-green w-50 fw-bold rounded-4 d-flex flex-column align-items-center justify-content-center"
              role="button">
              <i class="bi bi-file-earmark-text fs-1"></i>
              <span>Atividades</span>
            </a>
          </div>
        </div>
      </div>
    </div>
    {% empty %}
    <h1 class="display-3">Você não está matriculado em nenhuma disciplina!</h1>
    {% endfor %}
  </div>
</div>
{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script>
  $(document).ready(function () {
    $('#search-subject, #search-class').on('keyup', function () {
      var subjectInput = $('#search-subject').val().toLowerCase();
      var classInput = $('#search-class').val().toLowerCase();

      $('.row .col').filter(function () {
        var subjectName = $(this).data('id').toLowerCase();
        var className = $(this).data('class').toLowerCase();
        $(this).toggle(subjectName.indexOf(subjectInput) > -1 && className.indexOf(classInput) > -1);
      });
    });
  });
</script>
{% endblock script %}

main/templates/main/lancar-aula.html
{% extends "base.html" %}

{% block title %}SGE-GP | Turmas{% endblock title %}

{% block head %}
<style>
  #id_class_diary {
    height: 12rem;
  }

  #id_attendance_list,
  .attendance_list-col {
    height: 100%;
  }

  .attendance_list-form-floating{
    height: 90%;
  }
</style>
{% endblock head %}

{% block aside %}
  {% include "main/snippets/aside.html" %}
{% endblock aside %}

{% block content %}
<div class="col-12 col-md-9">
  <h1>Lançar Aula</h1>
  <form method="post" class="row mt-3">
    {% if form.errors %}
    <div class="col-12">
    <div class="alert alert-danger alert-dismissible fade show">
      {% for field in form %}
        {% for error in field.errors %}
          <strong>{{ field.label }}:</strong> {{ error|escape }}
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <strong>Non-field error:</strong> {{ error|escape }}
      {% endfor %}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    </div>
    {% endif %}
    {% csrf_token %}
    {% load widget_tweaks %}
    <div class="col-12 col-md-6">
        <div class="form-floating mb-3">
          {% render_field form.subject placeholder=form.subject.label required=True class="form-control" %}
          <label for="{{ form.subject.id_for_label }}">{{ form.subject.label }}</label>
        </div>

      <div class="form-floating mb-3">
        {% render_field form.date placeholder=form.date.label required=True class="form-control" %}
        <label for="{{ form.date.id_for_label }}">{{ form.date.label }}</label>
      </div>

      <div class="form-floating mb-3">
        {% render_field form.class_diary placeholder=form.class_diary.label required=True class="form-control" %}
        <label for="{{ form.class_diary.id_for_label }}">{{ form.class_diary.label }}</label>
      </div>
    </div>
    <div class="col-12 col-md-6">
    <div class="mb-3 attendance_list-col">
      <div class="form-floating attendance_list-form-floating">
        {% render_field form.attendance_list required=True class="form-control" %}
        <label for="{{ form.attendance_list.id_for_label }}">{{ form.attendance_list.label }}</label>
      </div>
      <small class="form-text d-none d-md-block">
        Segure <kbd>Ctrl</kbd> para selecionar mais de um aluno.
      </small>
      <small class="form-text d-md-none">
        Toque e segure para selecionar mais de um aluno.
      </small>
    </div>
    </div>
    <div class="col-12 d-flex justify-content-center mt-3">
      <a href="{% url 'main:subjects' %}" class="btn bg-dark-green me-3" role="button" style="height: min-content;">
          <i class="bi bi-arrow-left"></i>
          Voltar
      </a>
      <button type="submit" class="btn bg-dark-green mb-2">Lançar Aula</button>
    </div>
  </form>
</div>
{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script>
$(document).ready(function() {
  select_subject = '<option>Selecione uma disciplina...</option>'
  $("#id_attendance_list").html(select_subject);

  $('#id_subject').change(function() {
    var subjectId = $(this).val();

    if (!subjectId) {
      $("#id_attendance_list").html(select_subject);
      return;
    }

    $.ajax({
      url: "{% url 'main:get_students_for_subject' %}",
      data: {
        'subject': subjectId
      },
      success: function(data) {
        var options = '';
        for (var i = 0; i < data.length; i++) {
          options += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
        }
        $("#id_attendance_list").html(options);
      }
    });
  });
});
</script>
{% endblock script %}

main/templates/main/meu-perfil.html
{% extends "base.html" %}

{% block title %}Meu Perfil{% endblock title %}

{% block aside %}
  {% include "main/snippets/aside.html" %}
{% endblock aside %}

{% block content %}
<div class="col-12 col-md-9">
  <div class="row justify-content-center g-2">
    <div class="col-8">
        <h3 class="text-success">Meu Perfil</h3>
        <hr>
        <h1 class="text-success mb-3" style="text-transform: capitalize;">
            {% if user.type == 'teacher' %}
              Professor
            {% elif user.type == 'coordinator' %}
                Coordenador
            {% elif user.type == 'guardian' %}
                Responsável
            {% else %}
                Aluno
            {% endif %}
        </h1>
        <p><b>Nome:</b> {{ user }}</p>
        {% if user.birthdate %}
            <p><b>Data de Nascimento:</b> {{ user.birthdate }}</p>
            <p><b>Idade:</b> {{ user.age }}</p>
        {% endif %}
        <a href="{% url 'user_update' %}" class="text-success">Deseja mudar algo? Clique aqui. </a>
    </div>
    <div class="col-4">
        <figure class="d-flex flex-column align-items-center">
            <div class="ratio ratio-1x1 rounded-circle overflow-hidden border border-success">
                <img src="https://beforeigosolutions.com/wp-content/uploads/2021/12/dummy-profile-pic-300x300-1.png" alt="Imagem de {{ user.first_name }} {{ user.last_name }}" class="object-fit-cover">
            </div>
            <figcaption class="h3 text-success mt-2">{{ user.first_name }} {{ user.last_name }}</figcaption>
        </figure>
    </div>
</div>
{% endblock content %}