SGE_GP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('meu-perfil/', MeuPerfilView.as_view(), name='my-profile'),
    path("disciplinas/", DisciplinasView.as_view(), name="subjects"),
    path("disciplinas/<int:pk>/desempenho/", DesempenhoView.as_view(), name="performance"),
    path("lancar-aula/", LancarAulaView.as_view(), name="launch-class"),
    path('get_students_for_subject/', get_students_for_subject, name='get_students_for_subject'),
    path("professores/", ProfessoresView.as_view(), name="teachers"),
    # Avaliações
    path("avaliacoes/<str:slug>", TestsView.as_view(), name="tests"),
    path("avaliacoes/<str:slug>/abrir/", AbrirAvaliacaoView.as_view(), name="open-test"),
    path("avaliacoes/<int:pk>/", GradesView.as_view(), name="grades"),
    # Eventos
    path("eventos/", EventosView.as_view(), name="events"),
    path("eventos/<int:pk>/", EventoView.as_view(), name="event"),
    path("eventos/<int:pk>/editar/", EditarEvento.as_view(), name="edit-event"),
    path("criar-evento/", CriarEvento.as_view(), name="create-event"),
    path("eventos/<int:pk>/deletar/", DeletarEvento.as_view(), name="delete-event"),
    # Turmas
    path("turmas/", TurmasView.as_view(), name="classes"),
    path('turmas/<int:pk>/', TurmaDetailView.as_view(), name='class'),
    path('turmas/<int:pk>/editar', TurmaUpdateView.as_view(), name='edit-class'),
    path("turmas/criar/", TurmaCreateView.as_view(), name="create-class"),
    # Atividades
    path("disciplinas/<str:slug>/atividades/", ActivityListView.as_view(), name="activities"),
    path("disciplinas/<str:slug>/atividades/<int:pk>/", ActivityDetailView.as_view(), name="activity"),
    path("disciplinas/<str:slug>/atividades/criar/", ActivityCreateView.as_view(), name="create-activity"),
    path("disciplinas/<str:slug>/atividades/<int:pk>/editar/", ActivityUpdateView.as_view(), name="edit-activity"),
    path("disciplinas/<str:slug>/atividades/<int:pk>/deletar/", ActivityDeleteView.as_view(), name="delete-activity"),
]

main/models.py
from django.db import models
from django.utils.text import slugify


class Subject(models.Model):
    name = models.CharField("Nome", max_length=50)
    syllabus = models.TextField("Ementa", blank=True, null=True)
    class_code = models.ForeignKey(
        "Class", on_delete=models.CASCADE, verbose_name="Turma"
    )
    academic_probation = models.ManyToManyField(
        "accounts.User", related_name="academic_probation", verbose_name="Dependência", blank=True
    )
    teacher = models.ForeignKey('accounts.User', on_delete=models.CASCADE, verbose_name='Professor', blank=True, null=True)
    slug = models.SlugField(max_length=200, editable=False, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.name} {self.class_code}")
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name + " - " + str(self.class_code)

    class Meta:
        verbose_name = "Disciplina"
        verbose_name_plural = "Disciplinas"


class Class(models.Model):
    LEVELS = (
        ("M", "Maternal"),
        ("J1", "Jardim 1"),
        ("J2", "Jardim 2"),
        ("1", "1ª Ano"),
        ("2", "2ª Ano"),
        ("3", "3ª Ano"),
        ("4", "4ª Ano"),
        ("5", "5ª Ano"),
        ("6", "6ª Ano"),
        ("7", "7ª Ano"),
        ("8", "8ª Ano"),
        ("9", "9ª Ano"),
        ("1M", "1º Ano - Médio"),
        ("2M", "2º Ano - Médio"),
        ("3M", "3º Ano - Médio"),
    )

    code = models.CharField("Código", max_length=10)
    level = models.CharField("Nível", max_length=50, choices=LEVELS)
    enrolled = models.ManyToManyField(
        "accounts.User", related_name="matriculados", verbose_name="Matriculados", blank=True
    )
    academic_year = models.IntegerField("Ano Letivo")

    class Meta:
        verbose_name = "Turma"
        verbose_name_plural = "Turmas"

    def __str__(self):
        return self.code + " - " + self.level + " - " + str(self.academic_year)


class Classroom(models.Model):
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, verbose_name="Disciplina"
    )
    class_code = models.ForeignKey(
        Class, on_delete=models.CASCADE, verbose_name="Turma"
    )
    date = models.DateField("Data")
    attendance_list = models.ManyToManyField(
        "accounts.User",
        related_name="students_present",
        verbose_name="lista de presença",
    )
    class_diary = models.TextField("Diário de Classe")
    
    def get_absent_students(self):
        all_students = set(self.class_code.enrolled.all())
        present_students = set(self.attendance_list.all())
        absent_students = all_students - present_students
        return absent_students

    class Meta:
        verbose_name = "Aula"
        verbose_name_plural = "Aulas"

    def __str__(self):
        return str(self.subject.name) + " - " + str(self.class_code) + " - " + str(self.date)

class Test(models.Model):
    TESTS = (
        ("1", "1ª Avaliação"),
        ("2", "2ª Avaliação"),
        ("3", "3ª Avaliação"),
        ("4", "4ª Avaliação"),
        ("PF", "Prova Final"),
    )

    school_test = models.CharField("Prova", max_length=50, choices=TESTS)
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, verbose_name="Disciplina"
    )
    class_code = models.ForeignKey(
        Class, on_delete=models.CASCADE, verbose_name="Turma"
    )
    date = models.DateField("Data")

    class Meta:
        verbose_name = "Prova"
        verbose_name_plural = "Provas"

    def __str__(self):
        return self.get_school_test_display() + " de " + self.subject.name + " - " + str(self.class_code)


class Grade(models.Model):
    student = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, verbose_name="Aluno"
    )
    test = models.ForeignKey(Test, on_delete=models.CASCADE, verbose_name="Prova")
    grade = models.FloatField("Nota")

    class Meta:
        verbose_name = "Nota"
        verbose_name_plural = "Notas"

    def __str__(self):
        return (
            self.student.first_name
            + " - "
            + self.test.school_test
            + " - "
            + self.test.subject.name
            + " - "
            + str(self.test.class_code)
        )


class Activity(models.Model):
    title = models.CharField("Título", max_length=50)
    prompt = models.TextField("Enunciado")
    subject = models.ForeignKey(
        Subject, on_delete=models.CASCADE, verbose_name="Disciplina"
    )
    image = models.ImageField('Imagem', upload_to='main/activities', blank=True, null=True)
    creation_date = models.DateField("Data de criação", auto_now_add=True)
    delivery_date = models.DateField("Data de entrega")

    class Meta:
        verbose_name = "Atividade"
        verbose_name_plural = "Atividades"

    def __str__(self):
        return self.title


class Event(models.Model):
    image = models.ImageField('Imagem', upload_to='main/events', blank=True, null=True)
    title = models.CharField("Título", max_length=50)
    description = models.TextField("Descrição")
    date_time = models.DateTimeField("Data e Hora")
    enrolled = models.ManyToManyField(
        "accounts.User", related_name="participants", verbose_name="Participantes", blank=True
    )

    class Meta:
        verbose_name = "Evento"
        verbose_name_plural = "Eventos"

    def __str__(self):
        return self.title

main/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView

from .forms import ClassroomForm, TestForm, GradeForm
from accounts.models import User
from .models import *


class IndexView(TemplateView):
    template_name = "main/index.html"


class MeuPerfilView(LoginRequiredMixin, TemplateView):
    template_name = "main/meu-perfil.html"


class DisciplinasView(LoginRequiredMixin, ListView):
    model = Subject
    template_name = "main/disciplinas.html"
    context_object_name = "subjects"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.type == "teacher":
            context["subjects"] = Subject.objects.filter(teacher=self.request.user)
        elif self.request.user.type == "student":
            student = self.request.user
            try:
                student_class = Class.objects.get(enrolled=student)
                context["subjects"] = Subject.objects.filter(class_code=student_class)
            except Class.DoesNotExist:
                context["subjects"] = None
        return context
    
    
class DesempenhoView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Subject
    template_name = "main/desempenho.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        grades = Grade.objects.filter(student=self.request.user, test__subject=self.get_object())
        grades_dict = {grade.test.school_test: grade for grade in grades}
        context["grades"] = grades_dict
        
        # Calcula a média do aluno
        # Passo 1: Verifique se todas as notas estão presentes
        if all(grade in grades_dict for grade in ['1', '2', '3', '4']):
            # Passo 2: Calcule a média das primeiras 4 notas
            average = sum(grades_dict[grade].grade for grade in ['1', '2', '3', '4']) / 4

            # Passo 3: Verifique se há uma nota para a prova final
            if 'PF' in grades_dict:
                # Passo 4: Adicione a nota da prova final à média calculada e divida por 2
                average = (average + grades_dict['PF'].grade) / 2

            # Passo 5: Armazene o resultado na variável 'average'
            context["average"] = average

        # Get all the lessons of the subject
        lessons = Classroom.objects.filter(subject=self.get_object())

        # Get the student's absences
        absents = [lesson for lesson in lessons if self.request.user not in lesson.attendance_list.all()]
        context["absents"] = absents

        return context
    
    def test_func(self):    
        return self.request.user.type == "student"
    

def get_students_for_subject(request):
    subject = Subject.objects.get(id=request.GET.get('subject', None))
    students = subject.class_code.enrolled.all() | subject.academic_probation.all()
    student_list = [{'id': int(student.id), 'name': str(student)} for student in students]
    return JsonResponse(student_list, safe=False)


class LancarAulaView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Classroom
    form_class = ClassroomForm
    template_name = "main/lancar-aula.html"
    success_url = reverse_lazy("main:subjects")

    def get_form_kwargs(self):
        kwargs = super(LancarAulaView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs
    
    def form_valid(self, form):
        messages.success(self.request, "Aula lançada com sucesso!")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print(form.errors)
        messages.error(self.request, "Erro ao lançar aula.")
        return super().form_invalid(form)
    
    def test_func(self):    
        return self.request.user.type == "teacher" or self.request.user.type == "coordinator"
    

class ProfessoresView(LoginRequiredMixin, ListView):
    model = User
    template_name = "main/professores.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.type == "coordinator" or self.request.user.type == "teacher":
            context["teachers"] = User.objects.filter(type="teacher")
        else:
            try:
                student_class = Class.objects.get(enrolled=self.request.user)
                subjects = Subject.objects.filter(class_code=student_class)
                context["subjects"] = subjects
            except Class.DoesNotExist:
                context["subjects"] = None

        return context


class TestsView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Test
    template_name = "main/avaliacoes/avaliacoes.html"
    slug_field = "subject__slug"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tests"] = Test.objects.filter(subject__slug=self.kwargs["slug"])
        context["subject"] = Subject.objects.get(slug=self.kwargs["slug"])
        return context
    
    def test_func(self):    
        teacher = get_object_or_404(Subject, slug=self.kwargs['slug']).teacher
        return self.request.user == teacher or self.request.user.type == "coordinator"


class AbrirAvaliacaoView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Test
    form_class = TestForm
    template_name = "main/avaliacoes/abrir-avalicao.html"

    def get_success_url(self):
        return reverse_lazy("main:tests", kwargs={"slug": self.object.subject.slug})
    
    def get_form_kwargs(self):
        kwargs = super(AbrirAvaliacaoView, self).get_form_kwargs()
        subject = Subject.objects.get(slug=self.kwargs["slug"])
        kwargs.update({'user': self.request.user, 'subject': subject})
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["subject"] = Subject.objects.get(slug=self.kwargs["slug"])
        return context
    
    def test_func(self):    
        teacher = get_object_or_404(Subject, slug=self.kwargs['slug']).teacher
        return self.request.user == teacher or self.request.user.type == "coordinator"
    

class GradesView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Test
    template_name = "main/avaliacoes/notas.html"
    
    def test_func(self):    
        teacher = get_object_or_404(Test, pk=self.kwargs['pk']).subject.teacher
        return self.request.user == teacher or self.request.user.type == "coordinator"

    def get_success_url(self):
        return reverse_lazy("main:tests", kwargs={"slug": self.object.subject.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        students = self.object.subject.class_code.enrolled.all()
        student_form_pairs = []
        for student in students:
            grade = student.grade_set.filter(test=self.object).first()
            if grade is not None:
                grade.grade = str(grade.grade).replace(',', '.')
                grade.save()
            form = GradeForm(instance=grade)
            student_form_pairs.append((student, form))
        context['student_form_pairs'] = student_form_pairs
        return context

    def post(self, request, *args, **kwargs):   
        self.object = self.get_object()
        students = self.object.subject.class_code.enrolled.all()
        student_form_pairs = []
        for student in students:
            grade = student.grade_set.filter(test=self.object).first()
            if grade is None:
                grade = Grade(student=student, test=self.object)
            form = GradeForm(request.POST or None, prefix=str(student.id), instance=grade)
            if form.has_changed():
                if form.is_valid():
                    form.save()
                else:
                    print(f"Errors for student {student.id}: {form.errors}")
                    messages.error(request, "Erro ao lançar notas.")
                    return self.render_to_response(self.get_context_data(student_form_pairs=student_form_pairs))
            student_form_pairs.append((student, form))

        messages.success(request, "Notas lançadas com sucesso!")
        return redirect(self.get_success_url())
    
    
class EventosView(LoginRequiredMixin, ListView):
    model = Event
    template_name = "main/eventos/eventos.html"
    context_object_name = "events"
    
    
class EventoView(LoginRequiredMixin, DetailView):
    model = Event
    template_name = "main/eventos/evento.html"
    
    
class CriarEvento(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Event
    fields = ['image', 'title', 'description', 'date_time']
    template_name = "main/eventos/criar-evento.html"
    success_url = reverse_lazy("main:events")
    
    def test_func(self):    
        return self.request.user.type == "coordinator"
    

class EditarEvento(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Event
    fields = ['image', 'title', 'description', 'date_time']
    template_name = "main/eventos/criar-evento.html"
    success_url = reverse_lazy("main:events")
    
    def test_func(self):    
        return self.request.user.type == "coordinator"
    
    
class DeletarEvento(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Event

    def test_func(self):    
        return self.request.user.type == "coordinator"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy("main:events")
    

main/templates/main/atividades/activities.html
{% extends "base.html" %}

{% block title %}{{ subject.name }} | Atividades{% endblock title %}

{% block aside %}
{% include "main/snippets/aside.html" %}
{% endblock aside %}

{% block content %}
<div class="col-12 col-md-9">
    <div class="d-flex justify-content-between align-items-center w-100">
        <h1>Atividades</h1>
        {% if user.type == 'teacher' %}
        <a class="btn btn-success btn-sm" href="{% url 'main:create-activity' subject.slug %}" role="button"
            style="height: min-content;">
            <i class="bi bi-plus"></i>
            Criar Atividade
        </a>
        {% endif %}
    </div>
    <div class="list-group mt-3">
        {% for activity in activities %}
        <a href="{% url 'main:activity' subject.slug activity.pk %}"
            class="list-group-item list-group-item-action bg-light-green fw-bold">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ activity.title }}</h5>
                <small class="d-none d-md-block">Adicionada em {{ activity.creation_date|date:"d/m/Y" }}</small>
            </div>
            <p class="mb-1">{{ activity.prompt|slice:'39' }}...</p>
            <small class="text-muted">Entrega: {{ activity.delivery_date|date:"d/m/Y" }}</small>
        </a>
        {% empty %}
        <div class="alert alert-primary" role="alert">
            <strong>Opa!</strong> Não há atividades para os próximos dias!
        </div>
        {% endfor %}
    </div>
    <a href="{% url 'main:subjects' %}" class="btn bg-light-green mt-2" role="button"
        style="height: min-content;">
        <i class="bi bi-arrow-left"></i>
        Voltar
    </a>
</div>
{% endblock content %}

main/templates/main/atividades/activity.html
{% extends "base.html" %}

{% block title %}SGE-GP | Criar Evento{% endblock title %}

{% block head %}
<style>
    #id_description {
        min-height: 100%;
    }
</style>
{% endblock head %}

{% block aside %}
{% include "main/snippets/aside.html" %}
{% endblock aside %}

{% block content %}
<div class="col-12 col-md-9">
    <div class="row mb-2">
        <div class="col-12 col-md-6">
            <h1>{{ object.title }}</h1>
            <p>{{ object.prompt|linebreaks }}</p>
            <h6>Entrega em {{ object.delivery_date }}</h6>
        </div>
        <div class="col-12 col-md-6">
            <img src="{{ object.image.url }}" class="img-fluid object-fit-contain">
        </div>
    </div>
    <div class="row justify-content-between">
        <div class="col-auto">
            <a href="{% url 'main:activities' subject.slug %}" class="btn btn-success me-2" role="button"
                style="height: min-content;">
                <i class="bi bi-arrow-left"></i>
                Voltar
            </a>
            {% if has_permition %}              
            <button type="button" class="btn btn-danger me-2" data-bs-toggle="modal" data-bs-target="#deleteModal">
                <i class="bi bi-trash"></i>
                Excluir
            </button>

            <a href="{% url 'main:edit-activity' subject.slug object.pk %}" class="btn btn-warning me-2" role="button"
                style="height: min-content;">
                <i class="bi bi-pencil"></i>
                Editar
            </a>
            {% endif %}
            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Confirmar Exclusão</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Tem certeza de que deseja excluir este item?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                            <a href="{% url 'main:delete-activity' subject.slug object.pk %}" rol e="button"
                                class="btn btn-danger">
                                <i class="bi bi-trash"></i>
                                Excluir
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main/atividades/create-activity.html
{# title prompt image delivery_date #}
{% extends "base.html" %}

{% block title %}SGE-GP | Criar Evento{% endblock title %}

{% block head %}
<style>
    #id_prompt {
        min-height: 10rem;
    }
</style>
{% endblock head %}

{% block aside %}
    {% include "main/snippets/aside.html" %}
{% endblock aside %}

{% block content %}
<div class="col-12 col-md-9">
    <h1 class="text-center">Criar Atividade</h1>
    <form method="post" enctype="multipart/form-data" class="row justify-content-center">
        {% csrf_token %}
        {% load widget_tweaks %}
        <div class="col-12 col-md-6">
            <label class="form-label fw-bold" for="{{ form.image.id_for_label }}">{{ form.image.label }}:</label><br>
            {% render_field form.image placeholder=form.image.label required=True class="form-control" %}
            <div class="form-floating my-3">
                {% render_field form.title placeholder=form.title.label required=True class="form-control" %}
                <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
            </div>
            <div class="form-floating my-3">
                {% render_field form.prompt placeholder=form.prompt.label required=True class="form-control" %}
                <label for="{{ form.prompt.id_for_label }}">{{ form.prompt.label }}</label>
            </div>
            <div class="form-floating mb-3">
                {% render_field form.delivery_date placeholder=form.delivery_date.label required=True class="form-control" type='date' %}
                <label for="{{ form.delivery_date.id_for_label }}">{{ form.delivery_date.label }}</label>
            </div>
        </div>

        <div class="col-12 d-flex justify-content-center mt-3">
            <a href="{% url 'main:activities' subject.slug %}" class="btn btn-success me-2" role="button" style="height: min-content;">
                <i class="bi bi-arrow-left"></i>
                Voltar
            </a>
            <button type="submit" class="btn btn-success">Criar</button>
        </div>
    </form>
</div>
{% endblock content %}

main/templates/main/atividades/edit-activity.html
{# title prompt image delivery_date #}
{% extends "base.html" %}

{% block title %}SGE-GP | Criar Evento{% endblock title %}

{% block head %}
<style>
    #id_prompt {
        min-height: 10rem;
    }
</style>
{% endblock head %}

{% block aside %}
{% include "main/snippets/aside.html" %}
{% endblock aside %}

{% block content %}
<div class="col-12 col-md-9">
    <h1 class="text-center">Editar Atividade</h1>
    <form method="post" enctype="multipart/form-data" class="row justify-content-center">
        {% csrf_token %}
        {% load widget_tweaks %}
        <div class="col-12 col-md-6">
            <label class="form-label fw-bold" for="{{ form.image.id_for_label }}">{{ form.image.label }}:</label><br>
            {% render_field form.image placeholder=form.image.label required=True class="form-control" %}
            <div class="form-floating my-3">
                {% render_field form.title placeholder=form.title.label required=True class="form-control" %}
                <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
            </div>
            <div class="form-floating my-3">
                {% render_field form.prompt placeholder=form.prompt.label required=True class="form-control" %}
                <label for="{{ form.prompt.id_for_label }}">{{ form.prompt.label }}</label>
            </div>
            <div class="form-floating mb-3">
                {% render_field form.delivery_date placeholder=form.delivery_date.label required=True class="form-control" type='date' id='id_delivery_date' %}
                <label for="id_delivery_date">{{ form.delivery_date.label }}</label>
            </div>
        </div>

        <div class="col-12 d-flex justify-content-center mt-3">
            <a href="{% url 'main:activities' subject.slug %}" class="btn btn-success me-2" role="button" style="height: min-content;">
                <i class="bi bi-arrow-left"></i>
                Voltar
            </a>
            <button type="submit" class="btn btn-success">Salvar</button>
        </div>
    </form>
</div>
{% endblock content %}

{% block script %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var formattedDate = "{{ form.delivery_date.value|date:'Y-m-d' }}";
        document.getElementById('id_delivery_date').value = formattedDate;
    });
</script>
{% endblock script %}